# -*- coding: utf-8 -*-
"""todo_list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ioCPAhtg5cfFks2hp1xh6N2ttrq58SB2
"""

todo_list = []

def add_task():
    task = input("Enter your task: ")
    todo_list.append(task)
    print("Task added.")

def view_tasks():
    if not todo_list:
        print("No tasks added.")
    else:
        print("\nYour To-Do List:")
        for i, task in enumerate(todo_list, 1):
            print(f"{i}. {task}")

def delete_task():
    view_tasks()
    if todo_list:
        task_num = int(input("Enter task number to delete: "))
        if 0 < task_num <= len(todo_list):
            removed = todo_list.pop(task_num - 1)
            print(f"Deleted task: {removed}")
        else:
            print("Invalid task number.")

def main():
    while True:
        print("\nTo-Do List Options:")
        print("1. Add Task")
        print("2. View Tasks")
        print("3. Delete Task")
        print("4. Exit")

        choice = input("Choose an option: ")

        if choice == '1':
            add_task()
        elif choice == '2':
            view_tasks()
        elif choice == '3':
            delete_task()
        elif choice == '4':
            print("Goodbye!")
            break
        else:
            print("Invalid choice.")

main()